name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
         os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest, windows-latest, macos-26-intel, macos-26]
         python-version: ['3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv and python
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - run: uv run --frozen pytest
